class_name PathNetwork
extends RefCounted
## Strategic road graph generated by tools/generate_paths.py (paths.json).
## Roads are DATA + shader paint only - no meshes. Use it for AI routing hints,
## lane selection, camera bookmarks and debug. Unit movement itself uses the navmesh.

const PATHS_PATH := "res://terrain_data/paths.json"

## lane name -> ordered edge ids from base A to base B (center / left / right)
var lanes: Dictionary = {}
var nodes: Dictionary = {}        # name -> Vector3 (world position on the ground)
var edges: Dictionary = {}        # id -> {a, b, cls, lane, width, length, points: PackedVector3Array}
var summits: Dictionary = {}      # name -> Vector3
var chokes: Array = []            # [{lane, pos: Vector3, free_width}]
var open_areas: Array = []        # [{name, pos: Vector3, radius}]
var stats: Dictionary = {}

var _astar := AStar3D.new()
var _ids: Dictionary = {}         # node name -> astar id


static func load_default() -> PathNetwork:
	var f := FileAccess.open(PATHS_PATH, FileAccess.READ)
	if f == null:
		push_error("PathNetwork: missing %s - run tools/generate_paths.py" % PATHS_PATH)
		return null
	var n := PathNetwork.new()
	n._parse(JSON.parse_string(f.get_as_text()))
	return n


func _parse(d: Dictionary) -> void:
	lanes = d["lanes"]
	stats = d["stats"]
	for k in d["nodes"]:
		var p: Array = d["nodes"][k]
		nodes[k] = Vector3(p[0], p[1], p[2])
	for k in d["summits"]:
		var p: Array = d["summits"][k]
		summits[k] = Vector3(p[0], p[1], p[2])
	for c in d["chokes"]:
		chokes.append({"lane": c["lane"], "pos": Vector3(c["pos"][0], 0.0, c["pos"][1]), "free_width": c["free_width"]})
	for a in d["open_areas"]:
		open_areas.append({"name": a["name"], "pos": Vector3(a["pos"][0], 0.0, a["pos"][1]), "radius": a["radius"]})
	var i := 0
	for k in nodes:
		_astar.add_point(i, nodes[k])
		_ids[k] = i
		i += 1
	for e in d["edges"]:
		var pts := PackedVector3Array()
		for p in e["points"]:
			pts.append(Vector3(p[0], p[1], p[2]))
		edges[e["id"]] = {"a": e["a"], "b": e["b"], "cls": e["cls"], "lane": e["lane"],
				"width": e["width"], "length": e["length"], "points": pts}
		_astar.connect_points(_ids[e["a"]], _ids[e["b"]], true)


## Node names on the shortest strategic route (by straight node-to-node length).
func route(from_node: String, to_node: String) -> PackedStringArray:
	var out := PackedStringArray()
	if not _ids.has(from_node) or not _ids.has(to_node):
		return out
	for id in _astar.get_id_path(_ids[from_node], _ids[to_node]):
		out.append(nodes.keys()[id])
	return out


## Whole lane as one curve (base exit -> base exit) for formation / AI path hints.
func lane_curve(lane: String) -> Curve3D:
	var c := Curve3D.new()
	var first := true
	for eid in lanes.get(lane, []):
		var e: Dictionary = edges[eid]
		var pts: PackedVector3Array = e["points"]
		for i in pts.size():
			if not first and i == 0:
				continue
			c.add_point(pts[i])
		first = false
	return c


func lane_length(lane: String) -> float:
	var total := 0.0
	for eid in lanes.get(lane, []):
		total += edges[eid]["length"]
	return total


func nearest_node(p: Vector3) -> String:
	var best := ""
	var bd := INF
	for k in nodes:
		var d := (nodes[k] as Vector3).distance_squared_to(p)
		if d < bd:
			bd = d
			best = k
	return best
