class_name ResourceDatabase
extends RefCounted
## Read-only view of terrain_data/resources.json (generated by tools/generate_resources.py).
## Pure data for the future economy / AI / worker systems - no gameplay logic here.

const PATH := "res://terrain_data/resources.json"

enum Type { GOLD, WOOD, STONE, CRYSTAL }
const TYPE_NAMES := ["gold", "wood", "stone", "crystal"]

var locations: Array[Dictionary] = []     # every location, positions converted to Vector3
var by_id: Dictionary = {}
var economy: Dictionary = {}              # "type:tier" -> {amount, rate, regen, ...}
var stats: Dictionary = {}


static func load_default() -> ResourceDatabase:
	var f := FileAccess.open(PATH, FileAccess.READ)
	if f == null:
		push_error("ResourceDatabase: missing %s - run tools/generate_resources.py" % PATH)
		return null
	var db := ResourceDatabase.new()
	db._parse(JSON.parse_string(f.get_as_text()))
	return db


func _v3(a: Array) -> Vector3:
	return Vector3(a[0], a[1], a[2])


func _parse(d: Dictionary) -> void:
	economy = d["economy"]
	stats = d["stats"]
	for l in d["locations"]:
		var loc: Dictionary = l.duplicate(true)
		loc["position"] = _v3(l["position"])
		loc["gathering_point"] = _v3(l["gathering_point"])
		loc["approach_point"] = _v3(l["approach_point"])
		var slots: Array[Vector3] = []
		for s in l["slots"]:
			slots.append(_v3(s))
		loc["slots"] = slots
		locations.append(loc)
		by_id[loc["id"]] = loc


## owner: 0 / 1 = player, -1 = neutral (flank + central resources)
func for_owner(owner: int) -> Array[Dictionary]:
	return locations.filter(func(l): return l["owner"] == owner)


func of_type(type_name: String) -> Array[Dictionary]:
	return locations.filter(func(l): return l["type"] == type_name)


func of_tier(tier: String) -> Array[Dictionary]:
	return locations.filter(func(l): return l["tier"] == tier)


func nearest(from: Vector3, type_name := "") -> Dictionary:
	var best := {}
	var bd := INF
	for l in locations:
		if type_name != "" and l["type"] != type_name:
			continue
		var dd: float = (l["position"] as Vector3).distance_squared_to(from)
		if dd < bd:
			bd = dd
			best = l
	return best
